

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE TYPE "public"."user_role" AS ENUM (
    'admin',
    'user',
    'guest'
);


ALTER TYPE "public"."user_role" OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."update_event_status_function"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    SET "search_path" TO ''
    AS $$
BEGIN
    NEW.status = NOW() BETWEEN NEW.start_time AND NEW.end_time;
    RETURN NEW;
END;
$$;


ALTER FUNCTION "public"."update_event_status_function"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."ar_model" (
    "id" bigint NOT NULL,
    "model_name" "text" NOT NULL,
    "file_url" "text" NOT NULL,
    "thumbnail_url" "text",
    "description" "text",
    "created_by_user_id" "uuid" DEFAULT "auth"."uid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone
);


ALTER TABLE "public"."ar_model" OWNER TO "postgres";


ALTER TABLE "public"."ar_model" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."ar_model_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."event" (
    "id" bigint NOT NULL,
    "name" "text" NOT NULL,
    "description" "text",
    "start_time" timestamp with time zone,
    "end_time" timestamp with time zone,
    "organizer" "text",
    "status" boolean NOT NULL,
    "is_public" boolean NOT NULL,
    "created_by_user" "uuid" DEFAULT "auth"."uid"() NOT NULL,
    "image_url" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone NOT NULL
);


ALTER TABLE "public"."event" OWNER TO "postgres";


ALTER TABLE "public"."event" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."event_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."event_spot" (
    "id" bigint NOT NULL,
    "event_id" bigint,
    "spot_id" bigint,
    "order_in_event" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."event_spot" OWNER TO "postgres";


ALTER TABLE "public"."event_spot" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."event_spot_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."spots" (
    "id" bigint NOT NULL,
    "title" "text" NOT NULL,
    "subtitle" "text",
    "latitude" numeric NOT NULL,
    "logitude" numeric NOT NULL,
    "pin_color" "text" NOT NULL,
    "radius" integer,
    "image_url" "text",
    "description" "text",
    "category" integer,
    "ar_model_id" bigint,
    "address" "text" NOT NULL,
    "is_active" boolean NOT NULL,
    "created_by_user" "uuid" DEFAULT "auth"."uid"() NOT NULL,
    "updated_at" timestamp with time zone NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."spots" OWNER TO "postgres";


ALTER TABLE "public"."spots" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."spot_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."spot_visit" (
    "id" bigint NOT NULL,
    "user_id" "uuid" DEFAULT "auth"."uid"(),
    "spot_id" bigint,
    "event_id" bigint,
    "visited_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."spot_visit" OWNER TO "postgres";


ALTER TABLE "public"."spot_visit" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."spot_visit_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."user_profile" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "user_id" "uuid" DEFAULT "auth"."uid"() NOT NULL,
    "username" "text",
    "age" integer,
    "gender" integer,
    "address" "text",
    "updated_at" timestamp without time zone DEFAULT "now"(),
    "is_active" boolean,
    "last_login_at" timestamp with time zone DEFAULT "now"(),
    "role" "public"."user_role" DEFAULT 'user'::"public"."user_role" NOT NULL
);


ALTER TABLE "public"."user_profile" OWNER TO "postgres";


ALTER TABLE "public"."user_profile" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."user_profile_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."ar_model"
    ADD CONSTRAINT "ar_model_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."event"
    ADD CONSTRAINT "event_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."event_spot"
    ADD CONSTRAINT "event_spot_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."spots"
    ADD CONSTRAINT "spot_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."spot_visit"
    ADD CONSTRAINT "spot_visit_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."user_profile"
    ADD CONSTRAINT "user_profile_pkey" PRIMARY KEY ("id");



CREATE INDEX "idx_event_status_times" ON "public"."event" USING "btree" ("status", "start_time", "end_time");



CREATE OR REPLACE TRIGGER "update_event_status" BEFORE INSERT OR UPDATE ON "public"."event" FOR EACH ROW EXECUTE FUNCTION "public"."update_event_status_function"();



ALTER TABLE ONLY "public"."event_spot"
    ADD CONSTRAINT "event_spot_event_id_fkey" FOREIGN KEY ("event_id") REFERENCES "public"."event"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."event_spot"
    ADD CONSTRAINT "event_spot_spot_id_fkey" FOREIGN KEY ("spot_id") REFERENCES "public"."spots"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."spots"
    ADD CONSTRAINT "spot_ar_model_id_fkey" FOREIGN KEY ("ar_model_id") REFERENCES "public"."ar_model"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."spot_visit"
    ADD CONSTRAINT "spot_visit_event_id_fkey" FOREIGN KEY ("event_id") REFERENCES "public"."event"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."spot_visit"
    ADD CONSTRAINT "spot_visit_spot_id_fkey" FOREIGN KEY ("spot_id") REFERENCES "public"."spots"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."spot_visit"
    ADD CONSTRAINT "spot_visit_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."user_profile"
    ADD CONSTRAINT "user_profile_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



CREATE POLICY "Admin can all own AR models" ON "public"."ar_model" TO "authenticated" USING ((( SELECT "user_profile"."role"
   FROM "public"."user_profile"
  WHERE ("user_profile"."user_id" = ( SELECT "auth"."uid"() AS "uid"))) = 'admin'::"public"."user_role")) WITH CHECK ((( SELECT "user_profile"."role"
   FROM "public"."user_profile"
  WHERE ("user_profile"."user_id" = ( SELECT "auth"."uid"() AS "uid"))) = 'admin'::"public"."user_role"));



ALTER TABLE "public"."ar_model" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "create_policy" ON "public"."user_profile" FOR INSERT TO "authenticated" WITH CHECK ((( SELECT (( SELECT "auth"."uid"() AS "uid") = "user_profile"."user_id")) OR (( SELECT "user_profile_1"."role"
   FROM "public"."user_profile" "user_profile_1"
  WHERE ("user_profile_1"."user_id" = ( SELECT "auth"."uid"() AS "uid"))) = 'admin'::"public"."user_role")));



CREATE POLICY "delete_policy" ON "public"."user_profile" FOR DELETE TO "authenticated" USING ((( SELECT (( SELECT "auth"."uid"() AS "uid") = "user_profile"."user_id")) OR (( SELECT "user_profile_1"."role"
   FROM "public"."user_profile" "user_profile_1"
  WHERE ("user_profile_1"."user_id" = ( SELECT "auth"."uid"() AS "uid"))) = 'admin'::"public"."user_role")));



ALTER TABLE "public"."event" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "event_dalate_policy" ON "public"."event" FOR DELETE TO "authenticated" USING ((( SELECT "user_profile_1"."role"
   FROM "public"."user_profile" "user_profile_1"
  WHERE ("user_profile_1"."user_id" = ( SELECT "auth"."uid"() AS "uid"))) = 'admin'::"public"."user_role"));



CREATE POLICY "event_insert_policy" ON "public"."event" FOR INSERT TO "authenticated" WITH CHECK ((( SELECT "user_profile_1"."role"
   FROM "public"."user_profile" "user_profile_1"
  WHERE ("user_profile_1"."user_id" = ( SELECT "auth"."uid"() AS "uid"))) = 'admin'::"public"."user_role"));



CREATE POLICY "event_select_policy" ON "public"."event" FOR SELECT TO "authenticated" USING ((("is_public" = true) OR (( SELECT "user_profile_1"."role"
   FROM "public"."user_profile" "user_profile_1"
  WHERE ("user_profile_1"."user_id" = ( SELECT "auth"."uid"() AS "uid"))) = 'admin'::"public"."user_role")));



ALTER TABLE "public"."event_spot" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "event_spot_derate_policy" ON "public"."event_spot" FOR DELETE USING ((EXISTS ( SELECT 1
   FROM "public"."event"
  WHERE (("event"."id" = "event_spot"."event_id") AND (( SELECT "user_profile_1"."role"
           FROM "public"."user_profile" "user_profile_1"
          WHERE ("user_profile_1"."user_id" = ( SELECT "auth"."uid"() AS "uid"))) = 'admin'::"public"."user_role")))));



CREATE POLICY "event_spot_insert_policy" ON "public"."event_spot" FOR INSERT TO "authenticated" WITH CHECK ((EXISTS ( SELECT 1
   FROM "public"."event"
  WHERE (("event"."id" = "event_spot"."event_id") AND (( SELECT "user_profile_1"."role"
           FROM "public"."user_profile" "user_profile_1"
          WHERE ("user_profile_1"."user_id" = ( SELECT "auth"."uid"() AS "uid"))) = 'admin'::"public"."user_role")))));



CREATE POLICY "event_spot_select_policy" ON "public"."event_spot" FOR SELECT TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."event"
  WHERE (("event"."id" = "event_spot"."event_id") AND (("event"."is_public" = true) OR (( SELECT "user_profile"."role"
           FROM "public"."user_profile"
          WHERE ("user_profile"."user_id" = ( SELECT "auth"."uid"() AS "uid"))) = 'admin'::"public"."user_role"))))));



CREATE POLICY "event_spot_update_policy" ON "public"."event_spot" FOR UPDATE TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."event"
  WHERE (("event"."id" = "event_spot"."event_id") AND (( SELECT "user_profile_1"."role"
           FROM "public"."user_profile" "user_profile_1"
          WHERE ("user_profile_1"."user_id" = ( SELECT "auth"."uid"() AS "uid"))) = 'admin'::"public"."user_role"))))) WITH CHECK ((EXISTS ( SELECT 1
   FROM "public"."event"
  WHERE (("event"."id" = "event_spot"."event_id") AND (( SELECT "user_profile_1"."role"
           FROM "public"."user_profile" "user_profile_1"
          WHERE ("user_profile_1"."user_id" = ( SELECT "auth"."uid"() AS "uid"))) = 'admin'::"public"."user_role")))));



CREATE POLICY "event_update_policy" ON "public"."event" FOR UPDATE TO "authenticated" USING ((( SELECT "user_profile_1"."role"
   FROM "public"."user_profile" "user_profile_1"
  WHERE ("user_profile_1"."user_id" = ( SELECT "auth"."uid"() AS "uid"))) = 'admin'::"public"."user_role")) WITH CHECK ((( SELECT "user_profile_1"."role"
   FROM "public"."user_profile" "user_profile_1"
  WHERE ("user_profile_1"."user_id" = ( SELECT "auth"."uid"() AS "uid"))) = 'admin'::"public"."user_role"));



CREATE POLICY "select_policy" ON "public"."user_profile" FOR SELECT TO "authenticated" USING ((( SELECT (( SELECT "auth"."uid"() AS "uid") = "user_profile"."user_id")) OR (( SELECT "user_profile_1"."role"
   FROM "public"."user_profile" "user_profile_1"
  WHERE ("user_profile_1"."user_id" = ( SELECT "auth"."uid"() AS "uid"))) = 'admin'::"public"."user_role")));



CREATE POLICY "spot_delate_policy" ON "public"."spots" FOR DELETE TO "authenticated" USING ((( SELECT "user_profile_1"."role"
   FROM "public"."user_profile" "user_profile_1"
  WHERE ("user_profile_1"."user_id" = ( SELECT "auth"."uid"() AS "uid"))) = 'admin'::"public"."user_role"));



CREATE POLICY "spot_insert_policy" ON "public"."spots" FOR INSERT WITH CHECK ((( SELECT "user_profile_1"."role"
   FROM "public"."user_profile" "user_profile_1"
  WHERE ("user_profile_1"."user_id" = ( SELECT "auth"."uid"() AS "uid"))) = 'admin'::"public"."user_role"));



CREATE POLICY "spot_serect_policy" ON "public"."spots" FOR SELECT TO "authenticated" USING ((("is_active" = true) OR (( SELECT "user_profile_1"."role"
   FROM "public"."user_profile" "user_profile_1"
  WHERE ("user_profile_1"."user_id" = ( SELECT "auth"."uid"() AS "uid"))) = 'admin'::"public"."user_role")));



CREATE POLICY "spot_update_policy" ON "public"."spots" FOR UPDATE TO "authenticated" USING ((( SELECT "user_profile_1"."role"
   FROM "public"."user_profile" "user_profile_1"
  WHERE ("user_profile_1"."user_id" = ( SELECT "auth"."uid"() AS "uid"))) = 'admin'::"public"."user_role")) WITH CHECK ((( SELECT "user_profile_1"."role"
   FROM "public"."user_profile" "user_profile_1"
  WHERE ("user_profile_1"."user_id" = ( SELECT "auth"."uid"() AS "uid"))) = 'admin'::"public"."user_role"));



ALTER TABLE "public"."spot_visit" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "spot_visit_delate_policy" ON "public"."spot_visit" FOR DELETE TO "authenticated" USING ((( SELECT "user_profile_1"."role"
   FROM "public"."user_profile" "user_profile_1"
  WHERE ("user_profile_1"."user_id" = ( SELECT "auth"."uid"() AS "uid"))) = 'admin'::"public"."user_role"));



CREATE POLICY "spot_visit_insert_policy" ON "public"."spot_visit" FOR INSERT TO "authenticated" WITH CHECK ((( SELECT "user_profile_1"."role"
   FROM "public"."user_profile" "user_profile_1"
  WHERE ("user_profile_1"."user_id" = ( SELECT "auth"."uid"() AS "uid"))) = 'admin'::"public"."user_role"));



CREATE POLICY "spot_visit_select_policy" ON "public"."spot_visit" FOR SELECT TO "authenticated" USING ((("user_id" = "auth"."uid"()) OR (( SELECT "user_profile_1"."role"
   FROM "public"."user_profile" "user_profile_1"
  WHERE ("user_profile_1"."user_id" = ( SELECT "auth"."uid"() AS "uid"))) = 'admin'::"public"."user_role")));



CREATE POLICY "spot_visit_update_policy" ON "public"."spot_visit" FOR UPDATE TO "authenticated" USING ((( SELECT "user_profile_1"."role"
   FROM "public"."user_profile" "user_profile_1"
  WHERE ("user_profile_1"."user_id" = ( SELECT "auth"."uid"() AS "uid"))) = 'admin'::"public"."user_role")) WITH CHECK ((( SELECT "user_profile_1"."role"
   FROM "public"."user_profile" "user_profile_1"
  WHERE ("user_profile_1"."user_id" = ( SELECT "auth"."uid"() AS "uid"))) = 'admin'::"public"."user_role"));



ALTER TABLE "public"."spots" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "update_policy" ON "public"."user_profile" FOR UPDATE TO "authenticated" USING ((( SELECT (( SELECT "auth"."uid"() AS "uid") = "user_profile"."user_id")) OR (( SELECT "user_profile_1"."role"
   FROM "public"."user_profile" "user_profile_1"
  WHERE ("user_profile_1"."user_id" = ( SELECT "auth"."uid"() AS "uid"))) = 'admin'::"public"."user_role"))) WITH CHECK ((( SELECT (( SELECT "auth"."uid"() AS "uid") = "user_profile"."user_id")) OR (( SELECT "user_profile_1"."role"
   FROM "public"."user_profile" "user_profile_1"
  WHERE ("user_profile_1"."user_id" = ( SELECT "auth"."uid"() AS "uid"))) = 'admin'::"public"."user_role")));



ALTER TABLE "public"."user_profile" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

























































































































































GRANT ALL ON FUNCTION "public"."update_event_status_function"() TO "anon";
GRANT ALL ON FUNCTION "public"."update_event_status_function"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."update_event_status_function"() TO "service_role";


















GRANT ALL ON TABLE "public"."ar_model" TO "anon";
GRANT ALL ON TABLE "public"."ar_model" TO "authenticated";
GRANT ALL ON TABLE "public"."ar_model" TO "service_role";



GRANT ALL ON SEQUENCE "public"."ar_model_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."ar_model_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."ar_model_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."event" TO "anon";
GRANT ALL ON TABLE "public"."event" TO "authenticated";
GRANT ALL ON TABLE "public"."event" TO "service_role";



GRANT ALL ON SEQUENCE "public"."event_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."event_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."event_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."event_spot" TO "anon";
GRANT ALL ON TABLE "public"."event_spot" TO "authenticated";
GRANT ALL ON TABLE "public"."event_spot" TO "service_role";



GRANT ALL ON SEQUENCE "public"."event_spot_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."event_spot_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."event_spot_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."spots" TO "anon";
GRANT ALL ON TABLE "public"."spots" TO "authenticated";
GRANT ALL ON TABLE "public"."spots" TO "service_role";



GRANT ALL ON SEQUENCE "public"."spot_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."spot_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."spot_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."spot_visit" TO "anon";
GRANT ALL ON TABLE "public"."spot_visit" TO "authenticated";
GRANT ALL ON TABLE "public"."spot_visit" TO "service_role";



GRANT ALL ON SEQUENCE "public"."spot_visit_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."spot_visit_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."spot_visit_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."user_profile" TO "anon";
GRANT ALL ON TABLE "public"."user_profile" TO "authenticated";
GRANT ALL ON TABLE "public"."user_profile" TO "service_role";



GRANT ALL ON SEQUENCE "public"."user_profile_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."user_profile_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."user_profile_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";






























RESET ALL;
