drop trigger if exists "update_event_status" on "public"."event";

drop policy "Admin can all own AR models" on "public"."ar_model";

drop policy "event_dalate_policy" on "public"."event";

drop policy "event_insert_policy" on "public"."event";

drop policy "event_select_policy" on "public"."event";

drop policy "event_update_policy" on "public"."event";

drop policy "event_spot_derate_policy" on "public"."event_spot";

drop policy "spot_delate_policy" on "public"."spot";

drop policy "spot_insert_policy" on "public"."spot";

drop policy "spot_serect_policy" on "public"."spot";

drop policy "spot_update_policy" on "public"."spot";

drop policy "spot_visit_delate_policy" on "public"."spot_visit";

drop policy "create_policy" on "public"."user_profile";

drop policy "delete_policy" on "public"."user_profile";

drop policy "select_policy" on "public"."user_profile";

drop policy "update_policy" on "public"."user_profile";

drop policy "event_spot_insert_policy" on "public"."event_spot";

drop policy "event_spot_select_policy" on "public"."event_spot";

drop policy "event_spot_update_policy" on "public"."event_spot";

drop policy "spot_visit_insert_policy" on "public"."spot_visit";

drop policy "spot_visit_select_policy" on "public"."spot_visit";

drop policy "spot_visit_update_policy" on "public"."spot_visit";

revoke delete on table "public"."event" from "anon";

revoke insert on table "public"."event" from "anon";

revoke references on table "public"."event" from "anon";

revoke select on table "public"."event" from "anon";

revoke trigger on table "public"."event" from "anon";

revoke truncate on table "public"."event" from "anon";

revoke update on table "public"."event" from "anon";

revoke delete on table "public"."event" from "authenticated";

revoke insert on table "public"."event" from "authenticated";

revoke references on table "public"."event" from "authenticated";

revoke select on table "public"."event" from "authenticated";

revoke trigger on table "public"."event" from "authenticated";

revoke truncate on table "public"."event" from "authenticated";

revoke update on table "public"."event" from "authenticated";

revoke delete on table "public"."event" from "service_role";

revoke insert on table "public"."event" from "service_role";

revoke references on table "public"."event" from "service_role";

revoke select on table "public"."event" from "service_role";

revoke trigger on table "public"."event" from "service_role";

revoke truncate on table "public"."event" from "service_role";

revoke update on table "public"."event" from "service_role";

revoke delete on table "public"."spot" from "anon";

revoke insert on table "public"."spot" from "anon";

revoke references on table "public"."spot" from "anon";

revoke select on table "public"."spot" from "anon";

revoke trigger on table "public"."spot" from "anon";

revoke truncate on table "public"."spot" from "anon";

revoke update on table "public"."spot" from "anon";

revoke delete on table "public"."spot" from "authenticated";

revoke insert on table "public"."spot" from "authenticated";

revoke references on table "public"."spot" from "authenticated";

revoke select on table "public"."spot" from "authenticated";

revoke trigger on table "public"."spot" from "authenticated";

revoke truncate on table "public"."spot" from "authenticated";

revoke update on table "public"."spot" from "authenticated";

revoke delete on table "public"."spot" from "service_role";

revoke insert on table "public"."spot" from "service_role";

revoke references on table "public"."spot" from "service_role";

revoke select on table "public"."spot" from "service_role";

revoke trigger on table "public"."spot" from "service_role";

revoke truncate on table "public"."spot" from "service_role";

revoke update on table "public"."spot" from "service_role";

alter table "public"."spot" drop constraint "spot_ar_model_id_fkey";

alter table "public"."event_spot" drop constraint "event_spot_event_id_fkey";

alter table "public"."event_spot" drop constraint "event_spot_spot_id_fkey";

alter table "public"."spot_visit" drop constraint "spot_visit_event_id_fkey";

alter table "public"."spot_visit" drop constraint "spot_visit_spot_id_fkey";

alter table "public"."event" drop constraint "event_pkey";

alter table "public"."spot" drop constraint "spot_pkey";

drop index if exists "public"."event_pkey";

drop index if exists "public"."idx_event_status_times";

drop index if exists "public"."spot_pkey";

drop table "public"."event";

drop table "public"."spot";

create table "public"."events" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "description" text,
    "start_time" timestamp with time zone,
    "end_time" timestamp with time zone,
    "organizer" text,
    "status" boolean not null,
    "is_public" boolean not null,
    "created_by_user" uuid not null default auth.uid(),
    "image_url" text,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null
);


alter table "public"."events" enable row level security;

create table "public"."invitations" (
    "id" bigint generated always as identity not null,
    "email" text not null,
    "status" text not null default 'pending'::text,
    "invited_by" uuid not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone default now()
);


alter table "public"."invitations" enable row level security;

alter table "public"."spots" drop column "logitude";

alter table "public"."spots" add column "longitude" numeric not null;

alter table "public"."spots" alter column "address" drop not null;

alter table "public"."spots" alter column "id" add generated by default as identity;

alter table "public"."spots" alter column "is_active" set default false;

alter table "public"."spots" alter column "pin_color" drop not null;

alter table "public"."spots" alter column "updated_at" set default now();

alter table "public"."user_profile" add column "email" text;

CREATE UNIQUE INDEX invitations_email_key ON public.invitations USING btree (email);

CREATE UNIQUE INDEX invitations_pkey ON public.invitations USING btree (id);

CREATE UNIQUE INDEX user_profile_email_key ON public.user_profile USING btree (email);

CREATE UNIQUE INDEX event_pkey ON public.events USING btree (id);

CREATE INDEX idx_event_status_times ON public.events USING btree (status, start_time, end_time);

CREATE UNIQUE INDEX spot_pkey ON public.spots USING btree (id);

alter table "public"."events" add constraint "event_pkey" PRIMARY KEY using index "event_pkey";

alter table "public"."invitations" add constraint "invitations_pkey" PRIMARY KEY using index "invitations_pkey";

alter table "public"."spots" add constraint "spot_pkey" PRIMARY KEY using index "spot_pkey";

alter table "public"."invitations" add constraint "invitations_email_key" UNIQUE using index "invitations_email_key";

alter table "public"."invitations" add constraint "invitations_invited_by_fkey" FOREIGN KEY (invited_by) REFERENCES auth.users(id) not valid;

alter table "public"."invitations" validate constraint "invitations_invited_by_fkey";

alter table "public"."invitations" add constraint "invitations_status_check" CHECK ((status = ANY (ARRAY['pending'::text, 'accepted'::text, 'expired'::text]))) not valid;

alter table "public"."invitations" validate constraint "invitations_status_check";

alter table "public"."user_profile" add constraint "user_profile_email_key" UNIQUE using index "user_profile_email_key";

alter table "public"."event_spot" add constraint "event_spot_event_id_fkey" FOREIGN KEY (event_id) REFERENCES events(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."event_spot" validate constraint "event_spot_event_id_fkey";

alter table "public"."event_spot" add constraint "event_spot_spot_id_fkey" FOREIGN KEY (spot_id) REFERENCES spots(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."event_spot" validate constraint "event_spot_spot_id_fkey";

alter table "public"."spot_visit" add constraint "spot_visit_event_id_fkey" FOREIGN KEY (event_id) REFERENCES events(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."spot_visit" validate constraint "spot_visit_event_id_fkey";

alter table "public"."spot_visit" add constraint "spot_visit_spot_id_fkey" FOREIGN KEY (spot_id) REFERENCES spots(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."spot_visit" validate constraint "spot_visit_spot_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.get_invitations()
 RETURNS TABLE(id bigint, email text, status text, invited_by_email text, created_at timestamp with time zone)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
BEGIN
  -- 現在のユーザーが管理者かチェック
  IF NOT (SELECT public.is_admin()) THEN
    RAISE EXCEPTION 'Only administrators can view invitations';
  END IF;

  RETURN QUERY
  SELECT 
    i.id,
    i.email,
    i.status,
    u.email as invited_by_email,
    i.created_at
  FROM public.invitations i
  LEFT JOIN auth.users u ON i.invited_by = u.id
  ORDER BY i.created_at DESC;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$DECLARE
  invitation_exists boolean;
BEGIN
  -- user_profileレコードを作成
  INSERT INTO public.user_profile (user_id, email, role)
  VALUES (NEW.id, NEW.email, 'user'::public.user_role);

  -- 招待されているメールアドレスかチェック
  SELECT EXISTS (
    SELECT 1 
    FROM public.invitations 
    WHERE email = NEW.email AND status = 'pending'
  ) INTO invitation_exists;

  -- 招待されている場合はadminロールに変更
  IF invitation_exists THEN
    UPDATE public.user_profile 
    SET role = 'admin'::public.user_role 
    WHERE user_id = NEW.id;
    
    -- 招待ステータスを更新
    UPDATE public.invitations 
    SET status = 'accepted', updated_at = now() 
    WHERE email = NEW.email;
  END IF;

  RETURN NEW;
END;$function$
;

CREATE OR REPLACE FUNCTION public.handle_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
  -- new.updated_at = now(); は pg_catalog.now() と解釈されるため安全です
  new.updated_at = now();
  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.invite_admin(email_to_invite text)
 RETURNS json
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
DECLARE
  result json;
BEGIN
  -- 現在のユーザーが管理者かチェック
  IF NOT (SELECT public.is_admin()) THEN
    RETURN json_build_object(
      'success', false,
      'message', 'Only administrators can invite new admins'
    );
  END IF;

  -- 既に招待済みかチェック
  IF EXISTS (SELECT 1 FROM public.invitations WHERE email = email_to_invite) THEN
    RETURN json_build_object(
      'success', false,
      'message', 'Email already invited'
    );
  END IF;

  -- 招待レコードを作成
  INSERT INTO public.invitations (email, invited_by)
  VALUES (email_to_invite, (SELECT auth.uid()));

  RETURN json_build_object(
    'success', true,
    'message', 'Admin invitation sent successfully'
  );
END;
$function$
;

CREATE OR REPLACE FUNCTION public.is_admin()
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
BEGIN
  RETURN COALESCE(
    (SELECT public.user_profile.role = 'admin'::public.user_role
     FROM public.user_profile
     WHERE public.user_profile.user_id = (SELECT auth.uid())),
    false
  );
END;
$function$
;

grant delete on table "public"."events" to "anon";

grant insert on table "public"."events" to "anon";

grant references on table "public"."events" to "anon";

grant select on table "public"."events" to "anon";

grant trigger on table "public"."events" to "anon";

grant truncate on table "public"."events" to "anon";

grant update on table "public"."events" to "anon";

grant delete on table "public"."events" to "authenticated";

grant insert on table "public"."events" to "authenticated";

grant references on table "public"."events" to "authenticated";

grant select on table "public"."events" to "authenticated";

grant trigger on table "public"."events" to "authenticated";

grant truncate on table "public"."events" to "authenticated";

grant update on table "public"."events" to "authenticated";

grant delete on table "public"."events" to "service_role";

grant insert on table "public"."events" to "service_role";

grant references on table "public"."events" to "service_role";

grant select on table "public"."events" to "service_role";

grant trigger on table "public"."events" to "service_role";

grant truncate on table "public"."events" to "service_role";

grant update on table "public"."events" to "service_role";

grant delete on table "public"."invitations" to "anon";

grant insert on table "public"."invitations" to "anon";

grant references on table "public"."invitations" to "anon";

grant select on table "public"."invitations" to "anon";

grant trigger on table "public"."invitations" to "anon";

grant truncate on table "public"."invitations" to "anon";

grant update on table "public"."invitations" to "anon";

grant delete on table "public"."invitations" to "authenticated";

grant insert on table "public"."invitations" to "authenticated";

grant references on table "public"."invitations" to "authenticated";

grant select on table "public"."invitations" to "authenticated";

grant trigger on table "public"."invitations" to "authenticated";

grant truncate on table "public"."invitations" to "authenticated";

grant update on table "public"."invitations" to "authenticated";

grant delete on table "public"."invitations" to "service_role";

grant insert on table "public"."invitations" to "service_role";

grant references on table "public"."invitations" to "service_role";

grant select on table "public"."invitations" to "service_role";

grant trigger on table "public"."invitations" to "service_role";

grant truncate on table "public"."invitations" to "service_role";

grant update on table "public"."invitations" to "service_role";

create policy "ar_model_delete_policy"
on "public"."ar_model"
as permissive
for delete
to authenticated
using ((( SELECT is_admin() AS is_admin) OR (created_by_user_id = ( SELECT auth.uid() AS uid))));


create policy "ar_model_insert_policy"
on "public"."ar_model"
as permissive
for insert
to authenticated
with check ((( SELECT is_admin() AS is_admin) OR (created_by_user_id = ( SELECT auth.uid() AS uid))));


create policy "ar_model_select_policy"
on "public"."ar_model"
as permissive
for select
to authenticated
using (true);


create policy "ar_model_update_policy"
on "public"."ar_model"
as permissive
for update
to authenticated
using ((( SELECT is_admin() AS is_admin) OR (created_by_user_id = ( SELECT auth.uid() AS uid))))
with check ((( SELECT is_admin() AS is_admin) OR (created_by_user_id = ( SELECT auth.uid() AS uid))));


create policy "event_spot_delete_policy"
on "public"."event_spot"
as permissive
for delete
to authenticated
using ((EXISTS ( SELECT 1
   FROM events
  WHERE ((events.id = event_spot.event_id) AND (( SELECT is_admin() AS is_admin) OR (events.created_by_user = ( SELECT auth.uid() AS uid)))))));


create policy "event_delete_policy"
on "public"."events"
as permissive
for delete
to authenticated
using ((( SELECT is_admin() AS is_admin) OR (created_by_user = ( SELECT auth.uid() AS uid))));


create policy "event_insert_policy"
on "public"."events"
as permissive
for insert
to authenticated
with check ((( SELECT is_admin() AS is_admin) OR (created_by_user = ( SELECT auth.uid() AS uid))));


create policy "event_select_policy"
on "public"."events"
as permissive
for select
to authenticated
using (((is_public = true) OR ( SELECT is_admin() AS is_admin) OR (created_by_user = ( SELECT auth.uid() AS uid))));


create policy "event_update_policy"
on "public"."events"
as permissive
for update
to authenticated
using ((( SELECT is_admin() AS is_admin) OR (created_by_user = ( SELECT auth.uid() AS uid))))
with check ((( SELECT is_admin() AS is_admin) OR (created_by_user = ( SELECT auth.uid() AS uid))));


create policy "invitations_delete_policy"
on "public"."invitations"
as permissive
for delete
to authenticated
using (( SELECT is_admin() AS is_admin));


create policy "invitations_insert_policy"
on "public"."invitations"
as permissive
for insert
to authenticated
with check (( SELECT is_admin() AS is_admin));


create policy "invitations_select_policy"
on "public"."invitations"
as permissive
for select
to authenticated
using (( SELECT is_admin() AS is_admin));


create policy "invitations_update_policy"
on "public"."invitations"
as permissive
for update
to authenticated
using (( SELECT is_admin() AS is_admin))
with check (( SELECT is_admin() AS is_admin));


create policy "spot_visit_delete_policy"
on "public"."spot_visit"
as permissive
for delete
to authenticated
using ((( SELECT is_admin() AS is_admin) OR (user_id = ( SELECT auth.uid() AS uid))));


create policy "user_profile_delete_policy"
on "public"."user_profile"
as permissive
for delete
to authenticated
using ((( SELECT is_admin() AS is_admin) OR (user_id = ( SELECT auth.uid() AS uid))));


create policy "user_profile_insert_policy"
on "public"."user_profile"
as permissive
for insert
to authenticated
with check ((( SELECT is_admin() AS is_admin) OR (user_id = ( SELECT auth.uid() AS uid))));


create policy "user_profile_select_policy"
on "public"."user_profile"
as permissive
for select
to authenticated
using ((( SELECT is_admin() AS is_admin) OR (user_id = ( SELECT auth.uid() AS uid))));


create policy "user_profile_update_policy"
on "public"."user_profile"
as permissive
for update
to authenticated
using ((( SELECT is_admin() AS is_admin) OR (user_id = ( SELECT auth.uid() AS uid))))
with check ((( SELECT is_admin() AS is_admin) OR (user_id = ( SELECT auth.uid() AS uid))));


create policy "event_spot_insert_policy"
on "public"."event_spot"
as permissive
for insert
to authenticated
with check ((EXISTS ( SELECT 1
   FROM events
  WHERE ((events.id = event_spot.event_id) AND (( SELECT is_admin() AS is_admin) OR (events.created_by_user = ( SELECT auth.uid() AS uid)))))));


create policy "event_spot_select_policy"
on "public"."event_spot"
as permissive
for select
to authenticated
using ((EXISTS ( SELECT 1
   FROM events
  WHERE ((events.id = event_spot.event_id) AND ((events.is_public = true) OR ( SELECT is_admin() AS is_admin) OR (events.created_by_user = ( SELECT auth.uid() AS uid)))))));


create policy "event_spot_update_policy"
on "public"."event_spot"
as permissive
for update
to authenticated
using ((EXISTS ( SELECT 1
   FROM events
  WHERE ((events.id = event_spot.event_id) AND (( SELECT is_admin() AS is_admin) OR (events.created_by_user = ( SELECT auth.uid() AS uid)))))))
with check ((EXISTS ( SELECT 1
   FROM events
  WHERE ((events.id = event_spot.event_id) AND (( SELECT is_admin() AS is_admin) OR (events.created_by_user = ( SELECT auth.uid() AS uid)))))));


create policy "spot_visit_insert_policy"
on "public"."spot_visit"
as permissive
for insert
to authenticated
with check ((( SELECT is_admin() AS is_admin) OR (user_id = ( SELECT auth.uid() AS uid))));


create policy "spot_visit_select_policy"
on "public"."spot_visit"
as permissive
for select
to authenticated
using ((( SELECT is_admin() AS is_admin) OR (user_id = ( SELECT auth.uid() AS uid))));


create policy "spot_visit_update_policy"
on "public"."spot_visit"
as permissive
for update
to authenticated
using ((( SELECT is_admin() AS is_admin) OR (user_id = ( SELECT auth.uid() AS uid))))
with check ((( SELECT is_admin() AS is_admin) OR (user_id = ( SELECT auth.uid() AS uid))));


CREATE TRIGGER update_event_status BEFORE INSERT OR UPDATE ON public.events FOR EACH ROW EXECUTE FUNCTION update_event_status_function();

CREATE TRIGGER on_spots_updated BEFORE UPDATE ON public.spots FOR EACH ROW EXECUTE FUNCTION handle_updated_at();


