create type "public"."user_role" as enum ('admin', 'user', 'guest');

create table "public"."ar_model" (
    "id" bigint generated by default as identity not null,
    "model_name" text not null,
    "file_url" text not null,
    "thumbnail_url" text,
    "description" text,
    "created_by_user_id" uuid not null default auth.uid(),
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone
);


alter table "public"."ar_model" enable row level security;

create table "public"."event" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "description" text,
    "start_time" timestamp with time zone,
    "end_time" timestamp with time zone,
    "organizer" text,
    "status" boolean not null,
    "is_public" boolean not null,
    "created_by_user" uuid not null default auth.uid(),
    "image_url" text,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null
);


alter table "public"."event" enable row level security;

create table "public"."event_spot" (
    "id" bigint generated by default as identity not null,
    "event_id" bigint,
    "spot_id" bigint,
    "order_in_event" text,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."event_spot" enable row level security;

create table "public"."spot" (
    "id" bigint generated by default as identity not null,
    "title" text not null,
    "subtitle" text,
    "latitude" numeric not null,
    "logitude" numeric not null,
    "pin_color" text not null,
    "radius" integer,
    "image_url" text,
    "description" text,
    "category" integer,
    "ar_model_id" bigint,
    "address" text not null,
    "is_active" boolean not null,
    "created_by_user" uuid not null default auth.uid(),
    "updated_at" timestamp with time zone not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."spot" enable row level security;

create table "public"."spot_visit" (
    "id" bigint generated by default as identity not null,
    "user_id" uuid default auth.uid(),
    "spot_id" bigint,
    "event_id" bigint,
    "visited_at" timestamp with time zone not null default now()
);


alter table "public"."spot_visit" enable row level security;

create table "public"."user_profile" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid default auth.uid(),
    "username" text,
    "age" integer,
    "gender" integer,
    "address" text,
    "updated_at" timestamp without time zone default now(),
    "is_active" boolean,
    "last_login_at" timestamp with time zone default now(),
    "role" user_role not null default 'user'::user_role
);


alter table "public"."user_profile" enable row level security;

CREATE UNIQUE INDEX ar_model_pkey ON public.ar_model USING btree (id);

CREATE UNIQUE INDEX event_pkey ON public.event USING btree (id);

CREATE UNIQUE INDEX event_spot_pkey ON public.event_spot USING btree (id);

CREATE INDEX idx_event_status_times ON public.event USING btree (status, start_time, end_time);

CREATE UNIQUE INDEX spot_pkey ON public.spot USING btree (id);

CREATE UNIQUE INDEX spot_visit_pkey ON public.spot_visit USING btree (id);

CREATE UNIQUE INDEX user_profile_pkey ON public.user_profile USING btree (id);

alter table "public"."ar_model" add constraint "ar_model_pkey" PRIMARY KEY using index "ar_model_pkey";

alter table "public"."event" add constraint "event_pkey" PRIMARY KEY using index "event_pkey";

alter table "public"."event_spot" add constraint "event_spot_pkey" PRIMARY KEY using index "event_spot_pkey";

alter table "public"."spot" add constraint "spot_pkey" PRIMARY KEY using index "spot_pkey";

alter table "public"."spot_visit" add constraint "spot_visit_pkey" PRIMARY KEY using index "spot_visit_pkey";

alter table "public"."user_profile" add constraint "user_profile_pkey" PRIMARY KEY using index "user_profile_pkey";

alter table "public"."event_spot" add constraint "event_spot_event_id_fkey" FOREIGN KEY (event_id) REFERENCES event(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."event_spot" validate constraint "event_spot_event_id_fkey";

alter table "public"."event_spot" add constraint "event_spot_spot_id_fkey" FOREIGN KEY (spot_id) REFERENCES spot(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."event_spot" validate constraint "event_spot_spot_id_fkey";

alter table "public"."spot" add constraint "spot_ar_model_id_fkey" FOREIGN KEY (ar_model_id) REFERENCES ar_model(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."spot" validate constraint "spot_ar_model_id_fkey";

alter table "public"."spot_visit" add constraint "spot_visit_event_id_fkey" FOREIGN KEY (event_id) REFERENCES event(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."spot_visit" validate constraint "spot_visit_event_id_fkey";

alter table "public"."spot_visit" add constraint "spot_visit_spot_id_fkey" FOREIGN KEY (spot_id) REFERENCES spot(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."spot_visit" validate constraint "spot_visit_spot_id_fkey";

alter table "public"."spot_visit" add constraint "spot_visit_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."spot_visit" validate constraint "spot_visit_user_id_fkey";

alter table "public"."user_profile" add constraint "user_profile_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."user_profile" validate constraint "user_profile_user_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.update_event_status_function()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
BEGIN
    NEW.status = NOW() BETWEEN NEW.start_time AND NEW.end_time;
    RETURN NEW;
END;
$function$
;

grant delete on table "public"."ar_model" to "anon";

grant insert on table "public"."ar_model" to "anon";

grant references on table "public"."ar_model" to "anon";

grant select on table "public"."ar_model" to "anon";

grant trigger on table "public"."ar_model" to "anon";

grant truncate on table "public"."ar_model" to "anon";

grant update on table "public"."ar_model" to "anon";

grant delete on table "public"."ar_model" to "authenticated";

grant insert on table "public"."ar_model" to "authenticated";

grant references on table "public"."ar_model" to "authenticated";

grant select on table "public"."ar_model" to "authenticated";

grant trigger on table "public"."ar_model" to "authenticated";

grant truncate on table "public"."ar_model" to "authenticated";

grant update on table "public"."ar_model" to "authenticated";

grant delete on table "public"."ar_model" to "service_role";

grant insert on table "public"."ar_model" to "service_role";

grant references on table "public"."ar_model" to "service_role";

grant select on table "public"."ar_model" to "service_role";

grant trigger on table "public"."ar_model" to "service_role";

grant truncate on table "public"."ar_model" to "service_role";

grant update on table "public"."ar_model" to "service_role";

grant delete on table "public"."event" to "anon";

grant insert on table "public"."event" to "anon";

grant references on table "public"."event" to "anon";

grant select on table "public"."event" to "anon";

grant trigger on table "public"."event" to "anon";

grant truncate on table "public"."event" to "anon";

grant update on table "public"."event" to "anon";

grant delete on table "public"."event" to "authenticated";

grant insert on table "public"."event" to "authenticated";

grant references on table "public"."event" to "authenticated";

grant select on table "public"."event" to "authenticated";

grant trigger on table "public"."event" to "authenticated";

grant truncate on table "public"."event" to "authenticated";

grant update on table "public"."event" to "authenticated";

grant delete on table "public"."event" to "service_role";

grant insert on table "public"."event" to "service_role";

grant references on table "public"."event" to "service_role";

grant select on table "public"."event" to "service_role";

grant trigger on table "public"."event" to "service_role";

grant truncate on table "public"."event" to "service_role";

grant update on table "public"."event" to "service_role";

grant delete on table "public"."event_spot" to "anon";

grant insert on table "public"."event_spot" to "anon";

grant references on table "public"."event_spot" to "anon";

grant select on table "public"."event_spot" to "anon";

grant trigger on table "public"."event_spot" to "anon";

grant truncate on table "public"."event_spot" to "anon";

grant update on table "public"."event_spot" to "anon";

grant delete on table "public"."event_spot" to "authenticated";

grant insert on table "public"."event_spot" to "authenticated";

grant references on table "public"."event_spot" to "authenticated";

grant select on table "public"."event_spot" to "authenticated";

grant trigger on table "public"."event_spot" to "authenticated";

grant truncate on table "public"."event_spot" to "authenticated";

grant update on table "public"."event_spot" to "authenticated";

grant delete on table "public"."event_spot" to "service_role";

grant insert on table "public"."event_spot" to "service_role";

grant references on table "public"."event_spot" to "service_role";

grant select on table "public"."event_spot" to "service_role";

grant trigger on table "public"."event_spot" to "service_role";

grant truncate on table "public"."event_spot" to "service_role";

grant update on table "public"."event_spot" to "service_role";

grant delete on table "public"."spot" to "anon";

grant insert on table "public"."spot" to "anon";

grant references on table "public"."spot" to "anon";

grant select on table "public"."spot" to "anon";

grant trigger on table "public"."spot" to "anon";

grant truncate on table "public"."spot" to "anon";

grant update on table "public"."spot" to "anon";

grant delete on table "public"."spot" to "authenticated";

grant insert on table "public"."spot" to "authenticated";

grant references on table "public"."spot" to "authenticated";

grant select on table "public"."spot" to "authenticated";

grant trigger on table "public"."spot" to "authenticated";

grant truncate on table "public"."spot" to "authenticated";

grant update on table "public"."spot" to "authenticated";

grant delete on table "public"."spot" to "service_role";

grant insert on table "public"."spot" to "service_role";

grant references on table "public"."spot" to "service_role";

grant select on table "public"."spot" to "service_role";

grant trigger on table "public"."spot" to "service_role";

grant truncate on table "public"."spot" to "service_role";

grant update on table "public"."spot" to "service_role";

grant delete on table "public"."spot_visit" to "anon";

grant insert on table "public"."spot_visit" to "anon";

grant references on table "public"."spot_visit" to "anon";

grant select on table "public"."spot_visit" to "anon";

grant trigger on table "public"."spot_visit" to "anon";

grant truncate on table "public"."spot_visit" to "anon";

grant update on table "public"."spot_visit" to "anon";

grant delete on table "public"."spot_visit" to "authenticated";

grant insert on table "public"."spot_visit" to "authenticated";

grant references on table "public"."spot_visit" to "authenticated";

grant select on table "public"."spot_visit" to "authenticated";

grant trigger on table "public"."spot_visit" to "authenticated";

grant truncate on table "public"."spot_visit" to "authenticated";

grant update on table "public"."spot_visit" to "authenticated";

grant delete on table "public"."spot_visit" to "service_role";

grant insert on table "public"."spot_visit" to "service_role";

grant references on table "public"."spot_visit" to "service_role";

grant select on table "public"."spot_visit" to "service_role";

grant trigger on table "public"."spot_visit" to "service_role";

grant truncate on table "public"."spot_visit" to "service_role";

grant update on table "public"."spot_visit" to "service_role";

grant delete on table "public"."user_profile" to "anon";

grant insert on table "public"."user_profile" to "anon";

grant references on table "public"."user_profile" to "anon";

grant select on table "public"."user_profile" to "anon";

grant trigger on table "public"."user_profile" to "anon";

grant truncate on table "public"."user_profile" to "anon";

grant update on table "public"."user_profile" to "anon";

grant delete on table "public"."user_profile" to "authenticated";

grant insert on table "public"."user_profile" to "authenticated";

grant references on table "public"."user_profile" to "authenticated";

grant select on table "public"."user_profile" to "authenticated";

grant trigger on table "public"."user_profile" to "authenticated";

grant truncate on table "public"."user_profile" to "authenticated";

grant update on table "public"."user_profile" to "authenticated";

grant delete on table "public"."user_profile" to "service_role";

grant insert on table "public"."user_profile" to "service_role";

grant references on table "public"."user_profile" to "service_role";

grant select on table "public"."user_profile" to "service_role";

grant trigger on table "public"."user_profile" to "service_role";

grant truncate on table "public"."user_profile" to "service_role";

grant update on table "public"."user_profile" to "service_role";

create policy "Admin can all own AR models"
on "public"."ar_model"
as permissive
for all
to authenticated
using ((( SELECT user_profile.role
   FROM user_profile
  WHERE (user_profile.user_id = ( SELECT auth.uid() AS uid))) = 'admin'::user_role))
with check ((( SELECT user_profile.role
   FROM user_profile
  WHERE (user_profile.user_id = ( SELECT auth.uid() AS uid))) = 'admin'::user_role));


create policy "event_dalate_policy"
on "public"."event"
as permissive
for delete
to authenticated
using ((( SELECT user_profile_1.role
   FROM user_profile user_profile_1
  WHERE (user_profile_1.user_id = ( SELECT auth.uid() AS uid))) = 'admin'::user_role));


create policy "event_insert_policy"
on "public"."event"
as permissive
for insert
to authenticated
with check ((( SELECT user_profile_1.role
   FROM user_profile user_profile_1
  WHERE (user_profile_1.user_id = ( SELECT auth.uid() AS uid))) = 'admin'::user_role));


create policy "event_select_policy"
on "public"."event"
as permissive
for select
to authenticated
using (((is_public = true) OR (( SELECT user_profile_1.role
   FROM user_profile user_profile_1
  WHERE (user_profile_1.user_id = ( SELECT auth.uid() AS uid))) = 'admin'::user_role)));


create policy "event_update_policy"
on "public"."event"
as permissive
for update
to authenticated
using ((( SELECT user_profile_1.role
   FROM user_profile user_profile_1
  WHERE (user_profile_1.user_id = ( SELECT auth.uid() AS uid))) = 'admin'::user_role))
with check ((( SELECT user_profile_1.role
   FROM user_profile user_profile_1
  WHERE (user_profile_1.user_id = ( SELECT auth.uid() AS uid))) = 'admin'::user_role));


create policy "event_spot_derate_policy"
on "public"."event_spot"
as permissive
for delete
to public
using ((EXISTS ( SELECT 1
   FROM event
  WHERE ((event.id = event_spot.event_id) AND (( SELECT user_profile_1.role
           FROM user_profile user_profile_1
          WHERE (user_profile_1.user_id = ( SELECT auth.uid() AS uid))) = 'admin'::user_role)))));


create policy "event_spot_insert_policy"
on "public"."event_spot"
as permissive
for insert
to authenticated
with check ((EXISTS ( SELECT 1
   FROM event
  WHERE ((event.id = event_spot.event_id) AND (( SELECT user_profile_1.role
           FROM user_profile user_profile_1
          WHERE (user_profile_1.user_id = ( SELECT auth.uid() AS uid))) = 'admin'::user_role)))));


create policy "event_spot_select_policy"
on "public"."event_spot"
as permissive
for select
to authenticated
using ((EXISTS ( SELECT 1
   FROM event
  WHERE ((event.id = event_spot.event_id) AND ((event.is_public = true) OR (( SELECT user_profile.role
           FROM user_profile
          WHERE (user_profile.user_id = ( SELECT auth.uid() AS uid))) = 'admin'::user_role))))));


create policy "event_spot_update_policy"
on "public"."event_spot"
as permissive
for update
to authenticated
using ((EXISTS ( SELECT 1
   FROM event
  WHERE ((event.id = event_spot.event_id) AND (( SELECT user_profile_1.role
           FROM user_profile user_profile_1
          WHERE (user_profile_1.user_id = ( SELECT auth.uid() AS uid))) = 'admin'::user_role)))))
with check ((EXISTS ( SELECT 1
   FROM event
  WHERE ((event.id = event_spot.event_id) AND (( SELECT user_profile_1.role
           FROM user_profile user_profile_1
          WHERE (user_profile_1.user_id = ( SELECT auth.uid() AS uid))) = 'admin'::user_role)))));


create policy "spot_delate_policy"
on "public"."spot"
as permissive
for delete
to authenticated
using ((( SELECT user_profile_1.role
   FROM user_profile user_profile_1
  WHERE (user_profile_1.user_id = ( SELECT auth.uid() AS uid))) = 'admin'::user_role));


create policy "spot_insert_policy"
on "public"."spot"
as permissive
for insert
to public
with check ((( SELECT user_profile_1.role
   FROM user_profile user_profile_1
  WHERE (user_profile_1.user_id = ( SELECT auth.uid() AS uid))) = 'admin'::user_role));


create policy "spot_serect_policy"
on "public"."spot"
as permissive
for select
to authenticated
using (((is_active = true) OR (( SELECT user_profile_1.role
   FROM user_profile user_profile_1
  WHERE (user_profile_1.user_id = ( SELECT auth.uid() AS uid))) = 'admin'::user_role)));


create policy "spot_update_policy"
on "public"."spot"
as permissive
for update
to authenticated
using ((( SELECT user_profile_1.role
   FROM user_profile user_profile_1
  WHERE (user_profile_1.user_id = ( SELECT auth.uid() AS uid))) = 'admin'::user_role))
with check ((( SELECT user_profile_1.role
   FROM user_profile user_profile_1
  WHERE (user_profile_1.user_id = ( SELECT auth.uid() AS uid))) = 'admin'::user_role));


create policy "spot_visit_delate_policy"
on "public"."spot_visit"
as permissive
for delete
to authenticated
using ((( SELECT user_profile_1.role
   FROM user_profile user_profile_1
  WHERE (user_profile_1.user_id = ( SELECT auth.uid() AS uid))) = 'admin'::user_role));


create policy "spot_visit_insert_policy"
on "public"."spot_visit"
as permissive
for insert
to authenticated
with check ((( SELECT user_profile_1.role
   FROM user_profile user_profile_1
  WHERE (user_profile_1.user_id = ( SELECT auth.uid() AS uid))) = 'admin'::user_role));


create policy "spot_visit_select_policy"
on "public"."spot_visit"
as permissive
for select
to authenticated
using (((user_id = auth.uid()) OR (( SELECT user_profile_1.role
   FROM user_profile user_profile_1
  WHERE (user_profile_1.user_id = ( SELECT auth.uid() AS uid))) = 'admin'::user_role)));


create policy "spot_visit_update_policy"
on "public"."spot_visit"
as permissive
for update
to authenticated
using ((( SELECT user_profile_1.role
   FROM user_profile user_profile_1
  WHERE (user_profile_1.user_id = ( SELECT auth.uid() AS uid))) = 'admin'::user_role))
with check ((( SELECT user_profile_1.role
   FROM user_profile user_profile_1
  WHERE (user_profile_1.user_id = ( SELECT auth.uid() AS uid))) = 'admin'::user_role));


create policy "create_policy"
on "public"."user_profile"
as permissive
for insert
to authenticated
with check ((( SELECT (( SELECT auth.uid() AS uid) = user_profile.user_id)) OR (( SELECT user_profile_1.role
   FROM user_profile user_profile_1
  WHERE (user_profile_1.user_id = ( SELECT auth.uid() AS uid))) = 'admin'::user_role)));


create policy "delete_policy"
on "public"."user_profile"
as permissive
for delete
to authenticated
using ((( SELECT (( SELECT auth.uid() AS uid) = user_profile.user_id)) OR (( SELECT user_profile_1.role
   FROM user_profile user_profile_1
  WHERE (user_profile_1.user_id = ( SELECT auth.uid() AS uid))) = 'admin'::user_role)));


create policy "select_policy"
on "public"."user_profile"
as permissive
for select
to authenticated
using ((( SELECT (( SELECT auth.uid() AS uid) = user_profile.user_id)) OR (( SELECT user_profile_1.role
   FROM user_profile user_profile_1
  WHERE (user_profile_1.user_id = ( SELECT auth.uid() AS uid))) = 'admin'::user_role)));


create policy "update_policy"
on "public"."user_profile"
as permissive
for update
to authenticated
using ((( SELECT (( SELECT auth.uid() AS uid) = user_profile.user_id)) OR (( SELECT user_profile_1.role
   FROM user_profile user_profile_1
  WHERE (user_profile_1.user_id = ( SELECT auth.uid() AS uid))) = 'admin'::user_role)))
with check ((( SELECT (( SELECT auth.uid() AS uid) = user_profile.user_id)) OR (( SELECT user_profile_1.role
   FROM user_profile user_profile_1
  WHERE (user_profile_1.user_id = ( SELECT auth.uid() AS uid))) = 'admin'::user_role)));


CREATE TRIGGER update_event_status BEFORE INSERT OR UPDATE ON public.event FOR EACH ROW EXECUTE FUNCTION update_event_status_function();


